### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by Shupacabras** [ryukau/LV2Plugins#7]
In order to compile in KDE Neon 18.04 I needed to modify in `lv2cvport/Makefile`

build: \
`#	CV_3PoleLP \`
`#	CV_AudioToCv \`
`#	CV_CvToAudio \`
`#	CV_DelayLP3 \`
`#	CV_DoubleFilter \`
`#	CV_ExpADSREnvelope \`
`#	CV_ExpPolyADEnvelope \`
`#	CV_Gate16 \`
`#	CV_HoldFilter \`
`#	CV_Invert \`
`#	CV_LinearADSREnvelope \`
`#	CV_LinearMap \`
`#	CV_LongAllpass \`
`#	CV_Multiply \`
`#	CV_NaiveDelay \`
`#	CV_NestedLongAllpass \`
`#	CV_ParabolicADEnvelope \`
`#	CV_PController \`
`#	CV_PolyLoopEnvelope \`
`#	CV_PTRSaw \`
`#	CV_PTRTrapezoid \`
`#	CV_RampFilter \`
`#	CV_RateLimiter \`
`#	CV_Sin \`
`#	CV_StereoGain \`
`#	CV_ExpLoopEnvelope \ `

and add `#include <unordered_map>`
in EnvelopedSine/ui.cpp, IterativeSinCluster/ui.cpp and LatticeReverb/ui.cpp

**Comment by ryukau** [comment]
Some includes were missing on CV plugins (Fixed in 419ba2052f59a9a6d35b4b2c52c9e436f2a914d1). It should now build without commenting out the CV plugins.

I setup CI for Ubuntu 18.04 to prevent same mistake for future.

If the problem still exists, feel free to reopen this issue or make another issue.

Thanks again for reporting the issue.

---

For context, discussion also happened on linuxmusicians forum.

- <https://linuxmusicians.com/viewtopic.php?p=118980#p118980>
